# Generated by Django 6.1 on 2026-08-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoive',
            new_name='Invoice',
        ),
    ]
